### ISSUE TITLE
Private upload

### ISSUE THREAD

**Issue by jadbox** [apivideo/typescript-video-uploader#6]
How do I specify private video upload via the upload contructor API?

**Comment by olivierapivideo** [comment]
Hi Jonathan,
This library is only intended to upload a video file on a previously created video. Creation of the video is usually made on the backend side. You can for instance use our nodejs api client with `_public: false` in the payload to create a private video (see https://github.com/apivideo/nodejs-api-client/blob/main/doc/api/VideosApi.md#create). 

Feel free to open another issue if this doesn't solve your problem.
